<template>
  <q-page padding>
    <div class="text-h4 q-mb-md text-center text-primary">
      Advanced Full-Stack Demo (Quasar + Express)
    </div>

    <!-- Git Workflow Section -->
    <q-card class="q-mb-md shadow-2">
      <q-card-section class="bg-blue-grey-1">
        <div class="text-h6 text-weight-bold">Git Workflow</div>
      </q-card-section>
      <q-card-section>
        <q-list bordered separator>
          <q-item v-for="(step, index) in gitSteps" :key="index" class="q-pa-sm">
            <q-item-section avatar>
              <q-badge :color="index % 2 === 0 ? 'primary' : 'secondary'" class="text-white">{{ index + 1 }}</q-badge>
            </q-item-section>
            <q-item-section>
              <q-item-label class="text-weight-medium">{{ step.title }}</q-item-label>
              <q-item-label caption class="text-grey-7">{{ step.detail }}</q-item-label>
            </q-item-section>
          </q-item>
        </q-list>
      </q-card-section>
    </q-card>

    <!-- Docker Concepts Section -->
    <q-card class="q-mb-md shadow-2">
      <q-card-section class="bg-blue-grey-1">
        <div class="text-h6 text-weight-bold">Docker Concepts</div>
      </q-card-section>
      <q-card-section>
        <q-list bordered separator>
          <q-item v-for="(item, index) in dockerItems" :key="index" class="q-pa-sm">
            <q-item-section>
              <q-item-label class="text-weight-medium">{{ item.title }}</q-item-label>
              <q-item-label caption class="text-grey-7">{{ item.detail }}</q-item-label>
            </q-item-section>
          </q-item>
        </q-list>
      </q-card-section>
    </q-card>

    <!-- API Data Section -->
    <q-card class="shadow-2" flat bordered>
      <q-card-section class="bg-primary text-white text-center">
        <div class="text-h6 text-weight-bold">Data from Backend API</div>
        <div class="text-subtitle2">Fetched from http://localhost:3000/api/demo</div>
      </q-card-section>
      <q-card-section class="text-center">
        <q-spinner v-if="loading" color="primary" size="3em" class="q-ma-md" />
        <div v-else-if="error" class="text-red q-pa-md text-center">
          <q-icon name="error" size="2em" class="q-mb-sm" />
          <div>Error loading data: {{ error }}</div>
        </div>
        <q-list v-else bordered separator class="rounded-borders q-mt-md">
          <q-item class="q-pa-md">
            <q-item-section avatar>
              <q-badge color="green" class="text-white text-weight-bold">Git</q-badge>
            </q-item-section>
            <q-item-section>
              <q-item-label class="text-weight-bold text-green">{{ apiData.git.title }}</q-item-label>
              <q-item-label caption class="text-grey-7">{{ apiData.git.detail }}</q-item-label>
            </q-item-section>
          </q-item>
          <q-item class="q-pa-md">
            <q-item-section avatar>
              <q-badge color="blue" class="text-white text-weight-bold">Docker</q-badge>
            </q-item-section>
            <q-item-section>
              <q-item-label class="text-weight-bold text-blue">{{ apiData.docker.title }}</q-item-label>
              <q-item-label caption class="text-grey-7">{{ apiData.docker.detail }}</q-item-label>
            </q-item-section>
          </q-item>
        </q-list>
        <q-btn v-if="!loading" color="primary" icon="refresh" @click="fetchData" class="q-mt-md" unelevated rounded>
          <q-tooltip>Refresh Data from API</q-tooltip>
          Refresh Data
        </q-btn>
      </q-card-section>
    </q-card>
  </q-page>
</template>

<script setup>
import { ref, onMounted } from 'vue';
import axios from 'axios';

const gitSteps = ref([
  { title: 'Initialize Repository', detail: 'Create a new Git repository and add initial files.' },
  { title: 'Create Feature Branch', detail: 'Create a new branch for the feature you are working on.' },
  { title: 'Make Changes', detail: 'Make your code changes and commit them.' },
  { title: 'Push Branch', detail: 'Push the branch to the remote repository.' },
  { title: 'Create Pull Request', detail: 'Create a pull request to merge your changes.' },
  { title: 'Code Review', detail: 'Have your code reviewed by team members.' },
  { title: 'Merge Pull Request', detail: 'Merge the pull request into the main branch.' }
]);

const dockerItems = ref([
  { title: 'Docker Images', detail: 'Blueprints for containers, containing the application and its dependencies.' },
  { title: 'Docker Containers', detail: 'Running instances of Docker images.' },
  { title: 'Docker Compose', detail: 'Tool for defining and running multi-container Docker applications.' },
  { title: 'Docker Volumes', detail: 'Mechanism for persisting data generated by and used by Docker containers.' },
  { title: 'Docker Networks', detail: 'Allow containers to communicate with each other and with the outside world.' }
]);

const apiData = ref({ git: {}, docker: {} });
const loading = ref(true);
const error = ref(null);

const fetchData = async () => {
  loading.value = true;
  error.value = null;
  try {
    const response = await axios.get(import.meta.env.VITE_API_URL + '/api/demo');
    apiData.value = response.data;
  } catch (err) {
    error.value = err.message;
    console.error('API Error:', err);
  } finally {
    loading.value = false;
  }
};

onMounted(fetchData);
</script>
